name: Prod deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  front-end-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: npm install and build
        run: |
          npm install
          VITE_API_BASE_URL=/api npm run build
          ls -l ./dist
      - name: SCP Files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "client/dist/*"
          target: "/var/www/bookbook"
  back-end-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Server
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      # - name: Build
      #   run: dotnet build --no-restore
      - name: Publish
        run: |
          dotnet publish ./src/Server.Api --nologo --output ./dist --configuration Release
          ls -l ./dist
      - name: SCP Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "Server/dist/*"
          target: "/var/www/bookbook-api"
